services:

  # Base images

  broken-base: &common
    image: broken-base
    build:
      context: .
      dockerfile: Docker/base.dockerfile

    volumes:
      - /usr/lib/wsl:/usr/lib/wsl # WSL .SOs
      - .:/app

    # "--gpus=all"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: all

  # Sanity checks, assertions

  eglinfo:
    image: eglinfo
    build:
      context: .
      dockerfile: Docker/eglinfo.dockerfile
    depends_on:
      - broken-base
    <<: *common

  # Actual software

  shaderflow:
    image: shaderflow
    build:
      context: .
      dockerfile: Docker/shaderflow.dockerfile
    depends_on:
      - broken-base
    <<: *common

  depthflow:
    image: depthflow
    build:
      context: .
      dockerfile: Docker/depthflow.dockerfile
    depends_on:
      - broken-base
    <<: *common
