site_name: Broken Source Software
site_description: Unified Documentation of Broken Source Software
repo_url: https://github.com/BrokenSource/BrokenSource
edit_uri: edit/Master/Docs/
repo_name: GitHub
site_author: Tremeschin
copyright: © 2023-2024, Tremeschin
docs_dir: Docs
site_dir: Build/Docs
nav:
  - Home:
    - index.md
    - Installation:
      - 🔥 Source Code: get.md
      - 📦 Releases: releases.md
      - 🚀 Upgrading: upgrading.md
      - ♻️ Uninstalling: uninstalling.md
    - Special:
      - 🧭 Roadmap: roadmap.md
      - 🔦 PyTorch: pytorch.md
      - 🌎 Contributing: contributing.md
      # - ❤️ Sponsoring: sponsoring.md
      # - Fixme: fixme.md
    - About:
      - 👤 Developers: developers.md
      - 💬 Contact: contact.md
      - ⚖️ License: license.md
  - Broken:
    - Code Reference: broken/reference/
  - ShaderFlow:
    - shaderflow/index.md
    - Code Reference: shaderflow/reference/
  # - DepthFlow:
  #   - Code Reference: depthflow/reference/
  # - Pianola:
    # - Code Reference: pianola/reference/
  # - SpectroNote:
  #   - Code Reference: spectronote/reference/
extra_css:
  - css/extra.css
theme:
  name: material
  logo: resources/images/broken.png
  favicon: resources/images/broken.png
  font:
    text: Roboto Slab
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.prune
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - toc.follow
    - navigation.footer
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tabs.link
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

plugins:
  - search
  - include-markdown
  - autorefs
  # - section-index
  - literate-nav
  - gen-files:
      scripts:
        - Docs/make.py
  - git-revision-date-localized:
      enable_creation_date: true
  - mkdocstrings:
      handlers:
        python:

          # https://mkdocstrings.github.io/python/usage
          options:

            # General
            show_bases: false
            show_source: true

            # Headings
            # heading_level: 2
            show_root_heading: true
            show_root_toc_entry: true
            show_root_full_path: true
            show_root_members_full_path: true
            show_object_full_path: false
            show_category_heading: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true

            # Members
            inherited_members: false
            members_order: "source"
            group_by_category: false
            show_submodules: false
            summary: true
            show_labels: true

            # Docstrings
            docstring_style: google
            docstring_section_style: list
            show_if_no_docstring: true

            # Signatures
            annotations_path: source
            show_signature: true
            show_signature_annotations: true
            signature_crossrefs: true
            separate_signature: false
            line_length: 60

  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
          remove_comments: true
      cache_safe: true

markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.magiclink
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      linenums: true
      use_pygments: true
      auto_title: true
      pygments_lang_class: true
  - toc:
      permalink: true
  - md_in_html
  - attr_list
  - tables
  - admonition
  - footnotes

extra:
  analytics:
    provider: google
    property: G-1S2RXTSLF2
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Tremeschin
      name: GitHub
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/Tremeschinni
      name: Twitter
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@Tremeschin
      name: YouTube
    - icon: fontawesome/brands/telegram
      link: https://t.me/BrokenSource
      name: Telegram
    - icon: fontawesome/brands/discord
      link: https://discord.gg/KjqvcYwRHm
      name: Discord
