[project.urls]
repository    = "https://github.com/BrokenSource/BrokenSource"
homepage      = "https://brokensource.github.io"
documentation = "https://brokensource.github.io"
issues        = "https://brokensource.github.io/contact"

[project]
name         = "broken-source"
version      = "0.1.1"
description  = "Broken Source Software Framework"
authors      = [{name="Tremeschin", email="29046864+Tremeschin@users.noreply.github.com"}]
readme       = "Readme.md"
dependencies = [
    "rich>=13.7.1",
    "dotmap>=1.3.30",
    "arrow>=1.3.0",
    "datetime>=5.5",
    "distro>=1.9.0",
    "toml>=0.10.2",
    "appdirs>=1.4.4",
    "attrs>=23.2.0",
    "numpy>=1.26.3",
    "typer>=0.10.0",
    "intervaltree>=3.1.0",
    "python-dotenv>=1.0.1",
    "pyfiglet>=1.0.2",
    "pyyaml>=6.0.1",
    "validators>=0.24.0",
    "pretty-errors>=1.2.25",
    "cachetools>=5.3.3",
    "pyturbojpeg>=1.7.3",
    "opencv-contrib-python>=4.9.0.80",
    "watchdog>=4.0.0",
    "schedule>=1.2.1",
    "thefuzz>=0.22.1",
    "tqdm>=4.64.1",
    "requests>=2.28.1",
    "pillow==10.2.0",
    "cattrs>=23.2.3",
    "ujson>=5.9.0",
    "requests-cache>=1.2.0",
    "pip>=24.0",
    "moderngl>=5.10.0",
    "glfw>=2.7.0",
    "imgui>=2.0.0",
    "glcontext>=2.5.0",
    "soundcard>=0.4.3",
    "audioread>=3.0.1",
    "numpy-quaternion>=2023.0.3",
    "opensimplex>=0.4.5",
    "pygame>=2.5.2",
    "pretty-midi>=0.2.10",
    "pyfluidsynth>=1.3.3",
    "midi2audio>=0.1.1",
    "samplerate>=0.2.1",
    "scipy>=1.12.0",
    "moderngl-window @ git+https://github.com/Tremeschin/moderngl-window",
    "streamlit>=1.33.0",
    "yt-dlp>=2024.3.10",
]
requires-python = ">=3.10"

[tool.rye]
managed = true
dev-dependencies = [
    "poethepoet>=0.25.0",
    "snakeviz>=2.2.0",
    "pyshortcuts>=1.9.0",
    "userpath>=1.9.2",
    "pytest>=8.1.1",
    "meson>=1.4.0",
    "ninja>=1.11.1.1",
    "tuna>=0.5.11",
    "mkdocs>=1.5.3",
    "mkdocstrings>=0.24.1",
    "mkdocstrings-python>=1.9.0",
    "mkdocs-gen-files>=0.5.0",
    "mkdocs-autorefs>=1.0.1",
    "mkdocs-literate-nav>=0.6.1",
    "mkdocs-section-index>=0.3.8",
    "mkdocs-material[imaging]>=9.5.16",
    "mkdocs-minify-plugin>=0.8.0",
    "mkdocs-git-revision-date-localized-plugin>=1.2.4",
    "markdown-include>=0.8.1",
]

[tool.rye.workspace]
members = [
    "Projects/DepthFlow",
    "Projects/Pianola",
    "Projects/ShaderFlow",
    "Projects/SpectroNote"
]

[project.scripts]
broken      = "Broken.__main__:main"
depthflow   = "DepthFlow.__main__:main"
pianola     = "Pianola.__main__:main"
spectronote = "SpectroNote.__main__:main"
shaderflow  = "ShaderFlow.__main__:main"

# # Hatchling

[build-system]
requires      = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
only-include = [
    "Broken",
    "Projects/DepthFlow/DepthFlow",
    "Projects/Pianola/Pianola",
    "Projects/ShaderFlow/ShaderFlow",
    "Projects/SpectroNote/SpectroNote",
]

[tool.hatch.build.targets.wheel.sources]
"Projects/DepthFlow/DepthFlow"     = "DepthFlow"
"Projects/Pianola/Pianola"         = "Pianola"
"Projects/ShaderFlow/ShaderFlow"   = "ShaderFlow"
"Projects/SpectroNote/SpectroNote" = "SpectroNote"

[tool.hatch.build.targets.sdist]
exclude = ["*"]

# # PyTorch

[tool.poe.tasks]
_transformers = "python -m pip install transformers==4.39.1"
_torch_base   = "python -m pip install torch==2.2.1 torchvision"
_torch_cuda   = "python -m pip install torch==2.2.1 torchvision --index-url https://download.pytorch.org/whl/cu118"
_torch_rocm   = "python -m pip install torch==2.2.1 torchvision --index-url https://download.pytorch.org/whl/rocm5.7"
_torch_cpu    = "python -m pip install torch==2.2.1 torchvision --index-url https://download.pytorch.org/whl/cpu"
_utorch       = "python -m pip uninstall -y torch torchvision"
base          = ["_utorch", "_torch_base", "_transformers"]
cuda          = ["_utorch", "_torch_cuda", "_transformers"]
rocm          = ["_utorch", "_torch_rocm", "_transformers"]
cpu           = ["_utorch", "_torch_cpu" , "_transformers"]

# # Ruff

[tool.ruff.format]
exclude = ["*"]

[tool.ruff.lint]
ignore = ["F401", "E402", "E701"]

# # Sources

# [[tool.rye.sources]]
# name = "default"
# url  = "https://pypi.org/simple"

# [[tool.rye.sources]]
# name = "torch"
# url  = "https://download.pytorch.org/whl/cpu"

# [[tool.rye.sources]]
# name = "torch-cuda"
# url  = "https://download.pytorch.org/whl/cu118"

# [[tool.rye.sources]]
# name = "torch-rocm"
# url  = "https://download.pytorch.org/whl/rocm5.7"
