[tool.poetry]
name = "Nebula"
version = "1.0"
description = "Broken Source Software Python Shared Code"
authors = ["Tremeschin"]
license = "AGPLv3-only"

[[tool.poetry.packages]]
include = "Nebula"

[tool.poetry.dependencies]
python = "^3.10"
rich = "^13.3.4"
dotmap = "^1.3.30"
arrow = "^1.2.3"
datetime = "^5.1"
distro = "^1.8.0"
forbiddenfruit = "^0.1.4"
loguru = "^0.7.0"
pygit2 = "^1.12.0"
requests = "^2.28.2"
toml = "^0.10.2"
typer = "^0.7.0"

[tool.poetry.scripts]
nebula = "Nebula.__main__:main"
