[project.urls]
repository    = "https://github.com/BrokenSource/BrokenSource"
homepage      = "https://brokensrc.dev"
documentation = "https://brokensrc.dev"
issues        = "https://brokensrc.dev/contact"

[project]
name         = "broken-source"
version      = "0.4.0.dev1"
description  = "🚀 Broken Source Software Framework and All Projects in One Place"
authors      = [{name="Tremeschin", email="29046864+Tremeschin@users.noreply.github.com"}]
readme       = "Readme.md"
license      = "AGPL-3.0"
dependencies = [
    # Data Structures
    "attrs>=23.2.0",
    "pydantic>=2.7.4",
    "dotmap>=1.3.30",
    "validators>=0.28.3",
    "intervaltree>=3.1.0",
    # Math
    "numpy-quaternion>=2023.0.4",
    "opensimplex>=0.4.5.1",
    "scipy>=1.14.0",
    "numpy==1.26.4",
    # Audio
    "pyfluidsynth>=1.3.3",
    "soundcard>=0.4.3",
    "audioread>=3.0.1",
    # OpenGL
    "glfw>=2.7.0",
    "glcontext>=2.5.0",
    "moderngl>=5.10.0",
    "moderngl-window>=2.4.6",
    "imgui>=2.0.0",
    "pygame>=2.6.0",
    # Image Processing
    "opencv-contrib-python>=4.10.0.84",
    "pillow>=10.3.0",
    # Internet
    "requests-cache>=1.2.1",
    "requests>=2.32.3",
    "setuptools>=70.1.1",
    "uv>=0.2.15",
    # Utils
    "arrow>=1.3.0",
    "rich>=13.7.1",
    "distro>=1.9.0",
    "appdirs>=1.4.4",
    "typer>=0.12.3",
    "tqdm>=4.66.4",
    "thefuzz>=0.22.1",
    "watchdog>=4.0.1",
    "python-dotenv>=1.0.1",
    "cachetools>=5.3.3",
    "pyfiglet>=1.0.2",
    "loguru>=0.7.2",
    "diskcache>=5.6.3",
    "python-magic>=0.4.27",
    # MIDI
    "midi2audio>=0.1.1",
    "pretty-midi>=0.2.10",
    "mido>=1.3.2",
    "python-rtmidi>=1.5.8",
    "toml>=0.10.2",
]
requires-python = ">=3.9"

[project.optional-dependencies]
website = [
    "mkdocs>=1.6.0",
    "mkdocstrings==0.24.1",
    "mkdocstrings-python==1.9.0",
    "mkdocs-gen-files>=0.5.0",
    "mkdocs-autorefs>=1.0.1",
    "mkdocs-literate-nav>=0.6.1",
    "mkdocs-section-index>=0.3.9",
    "mkdocs-material[imaging]>=9.5.27",
    "mkdocs-minify-plugin>=0.8.0",
    "mkdocs-git-revision-date-localized-plugin>=1.2.6",
    "mkdocs-include-markdown-plugin>=6.2.1",
    "mkdocs-site-urls>=0.2.0",
]
# resample = [
#     "samplerate>=0.2.1",
# ]
# staging = [
#     "pyturbojpeg>=1.7.3",
#     "streamlit>=1.35.0",
#     "yt-dlp>=2024.5.27",
#     "schedule>=1.2.2",
#     "toml>=0.10.2",
#     "pyyaml>=6.0.1",
# ]

[tool.rye]
managed = true
dev-dependencies = [
    # Development and Utilities
    "pytest-sugar>=1.0.0",
    "poethepoet>=0.26.1",
    # Profiling
    "snakeviz>=2.2.0",
    "tuna>=0.5.11",
    # Manager
    "userpath>=1.9.2",
    "pyshortcuts>=1.9.0",
]

[tool.rye.workspace]
members = [
    "Projects/*",
    "Private/*",
    "Meta/*",
]

[project.scripts]
broken = "Broken.__main__:main"

# # Hatchling

[build-system]
requires      = ["hatchling", "cmake"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
only-include = [
    "Broken",
    "Projects/DepthFlow/DepthFlow",
    "Projects/Pianola/Pianola",
    "Projects/ShaderFlow/ShaderFlow",
    "Projects/SpectroNote/SpectroNote",
]

[tool.hatch.build.targets.wheel.sources]
"Projects/DepthFlow/DepthFlow"     = "DepthFlow"
"Projects/Pianola/Pianola"         = "Pianola"
"Projects/ShaderFlow/ShaderFlow"   = "ShaderFlow"
"Projects/SpectroNote/SpectroNote" = "SpectroNote"

[tool.hatch.build.targets.sdist]
exclude = ["*"]

# # PyTorch

[tool.poe.tasks]
_transformers = "python -m pip install transformers"
_torch_base   = "python -m pip install torch==2.3.1 --index-url https://download.pytorch.org/whl/cpu"
_torch_cuda   = "python -m pip install torch==2.3.1 --index-url https://download.pytorch.org/whl/cu118"
_torch_rocm   = "python -m pip install torch==2.3.1 --index-url https://download.pytorch.org/whl/rocm6.0"
_torch_cpu    = "python -m pip install torch==2.3.1 --index-url https://download.pytorch.org/whl/cpu"
_del_torch    = "python -m pip uninstall -y torch"
base          = ["_del_torch", "_torch_base", "_transformers"]
cuda          = ["_del_torch", "_torch_cuda", "_transformers"]
rocm          = ["_del_torch", "_torch_rocm", "_transformers"]
cpu           = ["_del_torch", "_torch_cpu" , "_transformers"]

# # Ruff

[tool.ruff.format]
exclude = ["*"]

[tool.ruff.lint]
ignore = [
    "F401",
    "E402",
    "E701",
    "E741", # Don't tell the Electrical Engineers
]

# # Sources

# [[tool.rye.sources]]
# name = "default"
# url  = "https://pypi.org/simple"

# [[tool.rye.sources]]
# name = "torch-cpu"
# url  = "https://download.pytorch.org/whl/cpu"

# [[tool.rye.sources]]
# name = "torch-cuda"
# url  = "https://download.pytorch.org/whl/cu118"

# [[tool.rye.sources]]
# name = "torch-rocm"
# url  = "https://download.pytorch.org/whl/rocm6.0"

[tool.pyright]
exclude = [".venv/**"]

# Tests

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
    "-p no:cacheprovider",
    "--durations=0",
    "--no-header",
    "--tb=short",
    "-v",
    "-ra",
]
python_classes = "_PyTest"
python_files = [
    "Core/Broken*.py",
]
