[tool.poetry]
name = "Broken"
version = "2023.4.21"
description = "Broken Source Software Python Shared Code"
authors = ["Tremeschin"]
license = "AGPLv3-only"

[[tool.poetry.packages]]
include = "Broken"

[tool.poetry.dependencies]
python = "^3.10"
rich = "^13.3.4"
dotmap = "^1.3.30"
arrow = "^1.2.3"
datetime = "^5.1"
distro = "^1.8.0"
forbiddenfruit = "^0.1.4"
loguru = "^0.7.0"
pygit2 = "^1.12.0"
requests = "^2.28.2"
toml = "^0.10.2"
typer = "^0.7.0"
iteration-utilities = "^0.11.0"
brakeit = {path="./Broken/Brakeit", develop=true}

[tool.poetry.scripts]
broken = "Broken.__main__:main"

[tool.poetry.group.dev.dependencies]
isort = "^5.12.0"
pyclean = "^2.7.0"

[build-system]
requires = [ "poetry-core>=1.0.0",]
build-backend = "poetry.core.masonry.api"
