[tool.poetry]
name = "Broken"
version = "2023.7.24"
description = "Broken Source Software Python Shared Code"
authors = ["Tremeschin"]
license = "AGPLv3-only"

[[tool.poetry.packages]]
include = "Broken"

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
rich = "^13.3.4"
dotmap = "^1.3.30"
arrow = "^1.2.3"
datetime = "^5.1"
distro = "^1.8.0"
forbiddenfruit = "^0.1.4"
loguru = "^0.7.0"
requests = "^2.28.2"
toml = "^0.10.2"
typer = {git = "https://github.com/tiangolo/typer", rev = "refs/pull/567/merge"}
halo = "^0.0.31"
appdirs = "^1.4.4"
poetry = "^1.5.1"
tqdm = "^4.65.0"
requests-cache = "^1.0.1"
pillow = "^9.5.0"
aenum = "^3.1.15"
pyyaml = "^6.0"
watchdog = "^3.0.0"
schedule = "^1.2.0"
attrs = "^23.1.0"

[tool.poetry.scripts]
broken = "Broken.__main__:main"

[tool.poetry.group.dev.dependencies]
isort = "^5.12.0"
nuitka = "^1.6.5"
pyinstaller = "^5.13.0"
pysnooper = "^1.1.1"

[build-system]
requires = [ "poetry-core>=1.0.0",]
build-backend = "poetry.core.masonry.api"
