[tool.poetry]
name        = "Broken"
version     = "2024.1.2"
description = "Broken Source Software Framework"
authors     = ["Tremeschin <tremeschin@users.noreply.github.com>"]
license     = "AGPLv3-only"

[[tool.poetry.packages]]
include = "Broken"

[tool.poetry.dependencies]
python         = ">=3.10,<3.13"
rich           = "^13.3.4"
dotmap         = "^1.3.30"
arrow          = "^1.2.3"
datetime       = "^5.1"
distro         = "^1.8.0"
forbiddenfruit = "^0.1.4"
loguru         = "^0.7.0"
requests       = "^2.28.2"
toml           = "^0.10.2"
halo           = "^0.0.31"
appdirs        = "^1.4.4"
poetry         = "^1.5.1"
tqdm           = "^4.65.0"
pillow         = "^9.5.0"
aenum          = "^3.1.15"
watchdog       = "^3.0.0"
schedule       = "^1.2.0"
attrs          = "^23.1.0"
thefuzz        = "^0.19.0"
numpy          = "^1.25.2"
typer          = "^0.9.0"
intervaltree   = "^3.1.0"
meson          = "^1.2.1"
ninja          = "^1.11.1"
wheel          = "^0.41.3"
opensimplex    = "^0.4.5"
moderngl       = "^5.9.0"
poethepoet     = "^0.24.4"
python-dotenv  = "^1.0.0"

[tool.poetry.scripts]
broken = "Broken.__main__:main"

[tool.poetry.group.dev.dependencies]
isort       = "^5.12.0"
nuitka      = "^1.6.5"
pyinstaller = "^5.13.0"

[tool.poetry.group.staging.dependencies]
redis   = "^5.0.1"
fastapi = "^0.105.0"
uvicorn = "^0.24.0.post1"

[build-system]
requires      = [ "poetry-core>=1.0.0",]
build-backend = "poetry.core.masonry.api"
