name: 🐞 New Bug Report
description: Facing some unexpected behavior or error? Let me help you! •
title: Describe what went wrong to your best guess. Don't worry, we can edit it later
labels:
  - bug

body:
- type: markdown
  attributes:
    value: |
      > [!IMPORTANT]
      > - **Consider** getting in touch on [**Discord or Telegram**](https://brokensrc.dev/about/contact/) first
      > - **Languages** I speak: (🇺🇸 English) (🇧🇷 Portuguese)
      > - [**Markdown Cheatsheet**](https://learnxinyminutes.com/docs/markdown)

- type: dropdown
  attributes:
    label: Operating System
    description: Where you're experiencing and tested the problem
    options:
      - Windows 11
      - Windows 10
      - macOS (Apple Silicon)
      - macOS (Intel)
      - Linux (Ubuntu-like)
      - Linux (Fedora-like)
      - Linux (Arch-like)
      - Linux (Others)
      - N/A
    multiple: true
    default: 0
  validations:
    required: true

- type: dropdown
  attributes:
    label: Python Version
    description: |
      - **If running directly from Source Code**, Rye will use the `.python-version` file (Currently 3.11)
      - **If running from PyPI Wheels**, check yours Python version with `python -V`
    options:
      - Python 3.10
      - Python 3.11
      - Python 3.12
      - Python 3.13
      - N/A
    default: 1
  validations:
    required: true

- type: dropdown
  attributes:
    label: Runtime Enviroment
    description: Where are you running the project from
    options:
      - PyPI Wheels (pip, poetry, pdm, rye, etc)
      - Source Code (Install Scripts or Manual)
      - PyAPP Executables (experimental)
      - N/A
    default: 0
  validations:
    required: true

- type: dropdown
  attributes:
    label: GPU Vendor (if applicable)
    description: "**Not all projects use GPUs**. Some issues might be hardware specific, often shader compile errors, bad texture sizes, corrupted output video, etc."
    options:
      - N/A
      - NVIDIA (Proprietary)
      - NVIDIA (Nouveau)
      - AMDGPU (Proprietary)
      - AMDGPU (Mesa)
      - Intel Graphics
      - Intel Arc
    multiple: true
    default: 0
  validations:
    required: false

- type: markdown
  attributes:
    value: <hr>

- type: textarea
  attributes:
    label: Description
    description: |
      ⚠️ Issues might be file or hardware specific, if the project deals with audio or video at all
      - Report what (and how) a certain code or feature is failing, should be enough to get started
  validations:
    required: true

- type: textarea
  attributes:
    label: Reproducing (if applicable)
    description: |
      - You can provide a Python script, commands, gist and repo links, steps to reproduce the issue?
    render: python
  validations:
    required: false

- type: textarea
  attributes:
    label: Resources
    description: |
      - You can add Screenshots, Videos or Terminal outputs to help explain the issue (<kbd>CTRL+V</kbd> them!)
    render: shell
  validations:
    required: false

- type: textarea
  attributes:
    label: Solution
    description: |
      Any guess on what went wrong? You can provide a solution, workaround or the idea of one
      - Don't worry, leave it blank if you feel unsure!
  validations:
    required: false
