name: 🐞 Create a new bug report ticket
description: Facing some unexpected behavior or error? Let me help you! •
title: Describe what went wrong, to your best guess • don't worry, we can edit the title later
labels:
  - bug

body:
- type: markdown
  attributes:
    value: |
      > [!IMPORTANT]
      > - Only the [**latest versions**](https://brokensrc.dev/get/) of the Projects or **git main branch** are **supported**<sup>*1</sup>
      > - **Consider** getting in touch on [**Discord or Telegram**](https://brokensrc.dev/about/contact/) first
      > - Help with formatting: [**Markdown Cheatsheet**](https://learnxinyminutes.com/docs/markdown)
      <sub><i>*1: I can still help you, but please try the latest version first, or say what version you're on</i></sub>

- type: markdown
  attributes:
    value: <div align="center"><h2>📦 Platform & Environment 📦</h2></div>

- type: dropdown
  id: operating-system
  attributes:
    label: 🔘 Operating system
    description: |
      - Where are you experiencing the problem?
    options:
      - Windows 11
      - Windows 10
      - macOS (Apple Silicon)
      - macOS (Intel)
      - Linux (Ubuntu-like)
      - Linux (Fedora-like)
      - Linux (Arch-like)
      - Linux (Others)
      - N/A
    multiple: true
    default: 0
  validations:
    required: true

- type: dropdown
  id: runtime
  attributes:
    label: 🔘 Runtime enviroment
    description: |
      - Where are you running the project from?
    options:
      - PyPI Wheels (pip, poetry, pdm, rye, etc)
      - Source Code (Install scripts or manual)
      - PyAPP Executables (experimental)
      - N/A
    default: 0
  validations:
    required: true

- type: dropdown
  id: python-version
  attributes:
    label: 🔘 Python version
    description: |
      - **If running from Source Code**: Rye will use the `.python-version` (Currently 3.11)
      - **If running from PyPI Wheels**: Check the Python version with `python --version`
    options:
      - Python 3.10
      - Python 3.11
      - Python 3.12
      - Python 3.13
      - N/A
    default: 1
  validations:
    required: true

- type: dropdown
  id: gpu-vendor
  attributes:
    label: 🔘 GPU Vendor
    description: |
      - Some issues might be hardware specific, often shader compile errors, bad texture sizes, corrupted output video, etc.
      - ⚠️ **Hybrid systems:** ShaderFlow logs the GPU being used, switch on your OS if wrong one, else select all that apply
      - ⚠️ **Not all projects uses the GPU**, feel free to leave this blank if applicable
    options:
      - N/A
      - Apple Silicon
      - NVIDIA Desktop
      - NVIDIA Laptop
      - AMD Integrated (Vega)
      - AMD Desktop (RX)
      - AMD Laptop (RX)
      - Intel HD Graphics/Iris
      - Intel Desktop Arc
      - Intel Laptop Arc
    multiple: true
    default: 0
  validations:
    required: false

- type: markdown
  attributes:
    value: <div align="center"><h2>🔥 Issue details 🔥</h2></div>

- type: textarea
  id: description
  attributes:
    label: 🔘 Description
    description: |
      - ⚠️ **Issues might be file or hardware specific**, if the project deals with audio or video at all
      - Report what (and how) a certain code or feature is failing, should be enough to get started
      - Any guess on what went wrong? You can provide a solution, workaround or the idea of one
      - **Tip:** You can provide a Python script, commands, links, steps to reproduce the issue
      - **Tip:** You can <kbd>CTRL+V</kbd> Screenshots, Videos, to help explain the issue
  validations:
    required: true

- type: textarea
  id: traceback
  attributes:
    label: 🔘 Terminal Output
    description: |
      - Paste the full traceback, error message, or log file here
    render: shell
  validations:
    required: false

- type: markdown
  attributes:
    value: |
      ###### © CC-BY-4.0, Issue Template by [**Tremeschin**](https://github.com/Tremeschin) 🔥
