name: 🐞 Create a new bug report ticket
description: Facing some unexpected behavior or error? Let me help you! •
title: Describe what went wrong, to your best guess • don't worry, we can edit the title later
labels:
  - bug

body:
- type: markdown
  attributes:
    value: |
      > [!IMPORTANT]
      > - Only the [**latest versions**](https://brokensrc.dev/get/) of the Projects or **git main branch** are **supported**<sup>*1</sup>
      > - **Consider** getting in touch on [**Discord or Telegram**](https://brokensrc.dev/about/contact/) first
      > - Help with formatting: [**Markdown Cheatsheet**](https://learnxinyminutes.com/docs/markdown)
      <sub><i>*1: I can still help you, please try the latests version first, or include what version you're on</i></sub>

- type: markdown
  attributes:
    value: <div align="center"><h2>📦 Platform & Environment 📦</h2></div>

- type: dropdown
  id: operating-system
  attributes:
    label: 🔵 Operating system
    description: Where you're experiencing the problem
    options:
      - Windows 11
      - Windows 10
      - macOS (Apple Silicon)
      - macOS (Intel)
      - Linux (Ubuntu-like)
      - Linux (Fedora-like)
      - Linux (Arch-like)
      - Linux (Others)
      - N/A
    multiple: true
    default: 0
  validations:
    required: true

- type: dropdown
  id: runtime
  attributes:
    label: 🔴 Runtime enviroment
    description: Where are you running the project from
    options:
      - PyPI Wheels (pip, poetry, pdm, rye, etc)
      - Source Code (Install scripts or manual)
      - PyAPP Executables (experimental)
      - N/A
    default: 0
  validations:
    required: true

- type: dropdown
  id: python-version
  attributes:
    label: 🟡 Python version
    description: |
      - **If running from Source Code**, Rye will use the `.python-version` (currently 3.11)
      - **If running from PyPI Wheels**, check yours Python version with `python -V`
    options:
      - Python 3.10
      - Python 3.11
      - Python 3.12
      - Python 3.13
      - N/A
    default: 1
  validations:
    required: true

- type: dropdown
  id: gpu-vendor
  attributes:
    label: 🟢 GPU Vendor (if applicable)
    description: |
      - Some issues might be hardware specific, often shader compile errors, bad texture sizes, corrupted output video, etc.
      - Note: you might be running on the wrong GPU on **hybrid systems**, search how to switch GPUs on your OS
    options:
      - N/A
      - NVIDIA (Proprietary)
      - NVIDIA (Nouveau)
      - AMDGPU (Proprietary)
      - AMDGPU (Mesa)
      - Intel Graphics
      - Intel Arc
    multiple: true
    default: 0
  validations:
    required: false

- type: markdown
  attributes:
    value: <div align="center"><h2>🔥 Issue details 🔥</h2></div>

- type: textarea
  id: description
  attributes:
    label: 🔵 Description
    description: |
      - ⚠️ **Issues might be file or hardware specific**, if the project deals with audio or video at all
      - Report what (and how) a certain code or feature is failing, should be enough to get started
  validations:
    required: true

- type: textarea
  id: reproducing
  attributes:
    label: 🔴 Reproducing
    description: |
      - You can provide a Python script, commands, gist and repo links, steps to reproduce the issue
    render: python
  validations:
    required: false

- type: textarea
  id: resources
  attributes:
    label: 🟡 Resources
    description: |
      - You can <kbd>CTRL+V</kbd> Screenshots, Videos or Terminal outputs to help explain the issue!
    render: shell
  validations:
    required: false

- type: textarea
  id: solution
  attributes:
    label: 🟢 Solution
    description: |
      Any guess on what went wrong? You can provide a solution, workaround or the idea of one
      - Don't worry, leave it blank if you feel unsure!
  validations:
    required: false

- type: markdown
  attributes:
    value: |
      ###### © CC-BY-4.0, Issue Template by [**Tremeschin**](https://github.com/Tremeschin) 🔥
