name: release
on:
  workflow_dispatch:
  push:
    paths:
      - "Broken/Version.py"

jobs:
  wheels:
    name: Release Wheels
    runs-on: ubuntu-latest
    steps:
      - uses: BrokenSource/BrokenSource@main
        name: Broken Setup

      - name: Build wheels
        run: rye run broken pypi --publish
        env:
          PYPI_TOKEN: ${{secrets.PYPI_TOKEN}}

      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: Wheels
          path: Build/Wheels/*.whl

      - name: Create Release Tag
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git tag -a v$BROKEN_VERSION -m "Release v$BROKEN_VERSION"
          git push origin v$BROKEN_VERSION

  releases:
    name: Release (${{matrix.os}})
    needs: wheels
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-14]
    steps:
      - uses: BrokenSource/BrokenSource@main
        name: Broken Setup

      - name: Build DepthFlow release
        run: rye run broken depthflow release --torch

      - name: Build Pianola release
        run: rye run broken pianola release

      - name: Build ShaderFlow release
        run: rye run broken shaderflow release

      - name: Build SpectroNote release
        run: rye run broken spectronote release

      # Upload releases per project, multi-OS

      - name: Upload DepthFlow releases
        uses: actions/upload-artifact@v3
        with:
          name: depthflow
          path: Release/depthflow*

      - name: Upload Pianola releases
        uses: actions/upload-artifact@v3
        with:
          name: pianola
          path: Release/pianola*

      - name: Upload ShaderFlow releases
        uses: actions/upload-artifact@v3
        with:
          name: shaderflow
          path: Release/shaderflow*
