name: release
on:
  workflow_dispatch:
  push:
    paths:
      - "Broken/Version.py"

jobs:
  wheels:
    name: Release Wheels
    runs-on: ubuntu-latest
    steps:
      - uses: BrokenSource/BrokenSource@main
        name: Broken Setup

      - name: Build wheels
        run: rye run broken pypi --publish

      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: Wheels
          path: Build/Wheels/*.whl

  releases:
    name: Release (${{matrix.os}})
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-14]
    steps:
      - uses: BrokenSource/BrokenSource@main
        name: Broken Setup

      - name: Build DepthFlow release
        run: rye run broken depthflow release --torch

      - name: Build Pianola release
        run: rye run broken pianola release

      - name: Build ShaderFlow release
        run: rye run broken shaderflow release

      - name: Build SpectroNote release
        run: rye run broken spectronote release

      - name: Upload Releases artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Release
          path: Release/*
